services:
  - type: web
    name: poker-crm-backend
    env: node
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
